# -*- coding: utf-8 -*-
"""Lab6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o0h2avpgjY4H6cZsIQEx1l5hDug0Pn1w

Exercise 1: Write a program to generate n numbers in special sequences as follows
"""

import numpy as np

def f1a(n):
  return 4 * n + 1

def f1b(n):
  return 3**n

def f1c(n):
  return n**3

# Xem lại
def f1d(n): 
  if n < 0:
   return -1
  elif (n == 0 or n == 1):
    return n;
  else:
    return f1d(n-1) + f1d(n-2)

print("Exercise 1")

n = np.arange(1,11,1)

print("a) Dãy x(n) gồm các số")
for n0 in n:
  print("n = " + str(n0) + ", x(n) = 4 * n + 1 = ", f1a(n0))

print()

print("b) Dãy x(n) gồm các số")
for n0 in n:
  print("n = " + str(n0) + ", x(n) = 3**n = ", f1b(n0))

print()

print("c) Dãy x(n) gồm các số")
for n0 in n:
  print("n = " + str(n0) + ", x(n) = n**3 = ", f1c(n0))

print()

# Xem lại
print("d) Dãy x(n) gồm các số")
for n0 in n:
  print("n = " + str(n0) + ", x(n) = x(n-1) + x(n-2) = ", f1d(n0))

"""Exercise 2: Write a program to find the parameters of the corresponding sequences"""

from sympy import *

n = symbols('n')

print("Exercise 2a")

a1 = 5
a2 = 20
d = a2 - a1
f2a = a1 + (n - 1) * d # a(n) = a1 + (n - 1) * d
f2a_n = lambda n: a1 + (n - 1) * d

print("d = ",d)
print("a(n) = " + str(f2a))
print("a(55) = ",f2a_n(55))
print("a(n) = 230 => n = ",solve(f2a - 230)) # 5 + (n - 1) * 15 -230 = 0 => n =

print()

print("Exercise 2b")

a1 = 120
a2 = 60
r = a2 / a1
f2b = a1 * r**(n-1)
f2b_n = lambda n: a1 * r**(n-1)

print("r = ",r)
print("a(n) = " + str(f2b))
print("a(10) = ",f2b_n(10))
print("a(n) = 15/32 => n = ",solve(f2b - 15/32))